<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
       "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Paddleboarding FAQ</title>
<link rel="stylesheet" type="text/css" href="/hecdesk/test/stylesheet.css">
</head>
<body>
<h3 style="margin-left: 40px;">Paddleboarding FAQ</h3>
<div style="margin: 40px;"><br><p><span style="font-size: 13px;"><span style="font-family: Arial;"><strong>Q. What is paddleboarding?</strong></span></span></p>
<p><span style="font-size: 13px;"><span style="font-family: Arial;">A. Paddleboarding  is the newest water sport to hit the scene! It is one of the fastest growing watersports in Florida. Paddleboards allow you to easily catch waves and get a great workout at the same time. They are great for flat summer days or when there are nice rolling swells. <br />
</span></span></p>
<p><span style="font-size: 13px;"><span style="font-family: Arial;">As  well as being lots of fun, stand-up paddling is a very good aerobic and  strength training exercise - depending on how vigorously you attack it,  stand-up paddling can be anything from a comfortable cruise in the park  to a heart-pounding, calorie-burning workout that will leave you nicely  tired out and ready for a great dinner! Fishing, exploring, sailing . .  . the sky's the limit!</span></span></p>
<p><span style="font-size: 13px;"><span style="font-family: Arial;">Whether  you like to cruise the lake, drift down the river, troll the reefs,  travel between islands or hit the surf, stand-up paddling is the best  way to walk on water! Florida's beautiful outdoors are yours for the  paddling - waterways, rivers, lakes and the ocean all become your own  personal playground! Stand-up paddling - lots of fun, great exercise.</span></span></p>
<p align="left"><span style="font-size: 13px;"><span style="font-family: Arial;"><strong>Q. Is </strong></span></span><strong><a href="http://jupiterkiteboarding.com/store/index.php"><span style="font-size: 13px;"><span style="font-family: Arial;">paddleboarding</span></span></a></strong><span style="font-size: 13px;"><span style="font-family: Arial;"><strong> a safe sport?</strong></span></span></p>
<p align="left"><span style="font-size: 13px;"><span style="font-family: Arial;">A. Paddleboarding is a very safe sport, as long as   one selects conditions within his or her ability level. Paddleboards are large   pieces of equipment, that should be respected regardless of the water   conditions. Lessons help teach new riders safe and responsible paddleboarding   practices. </span></span></p>
<p align="left"><span style="font-size: 13px;"><span style="font-family: Arial;"><strong>Q. Do I need a </strong></span></span><strong><a href="http://www.jupiterkiteboarding.com/store/lessons-tours-c-612_588.html"><span style="font-size: 13px;"><span style="font-family: Arial;">lesson</span></span></a></strong><span style="font-size: 13px;"><span style="font-family: Arial;"><strong> to go paddleboarding?</strong></span></span></p>
<p align="left"><span style="font-size: 13px;"><span style="font-family: Arial;">A. Paddleboarding   lessons are a great idea to help new riders learn the basic skills. Normally   a few minutes of practice is all it takes to become self-sufficient. </span></span></p>
<p align="left"><span style="font-size: 13px;"><span style="font-family: Arial;"><strong>Q. How much are paddleboarding   lessons and demos?</strong></span></span></p>
<p align="left"><span style="font-size: 13px;"><span style="font-family: Arial;">A. If you follow this link, &quot;</span></span><a href="http://www.jupiterkiteboarding.com/store/lessons-tours-c-612_588.html"><span style="font-size: 13px;"><span style="font-family: Arial;">LESSONS HERE</span></span></a><span style="font-size: 13px;"><span style="font-family: Arial;">&quot;, you will find out it's not as much as you think to have an unforgettable and life changing experience!<br />
</span></span></p>
<p align="left"><span style="font-size: 13px;"><span style="font-family: Arial;"><strong>Q. Where can I go paddleboarding?</strong></span></span></p>
<p align="left"><span style="font-size: 13px;"><span style="font-family: Arial;">A. Paddleboarding is possible anywhere with enough   water. Locations with heavy boat traffic, strong currents, dangerous   outcroppings, and unforgiving conditions should be avoided. Keep a safe distance   from swimming areas at local beaches, so as not to become a danger to other   swimmers or surfers. </span></span></p>
<h1><a href="http://jupiterkiteboarding.com/store/index.php">Next: Let's Shop!</a></h1> </div></body></html> 