<?php
$html_email_order = "<html>";
$html_email_order .= "<head>";
$html_email_order .= "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"> ";
$html_email_order .= "$Varhttp ";
$html_email_order .= "$Varstyle ";
$html_email_order .= "</head>";
$html_email_order .= "<body>";
$html_email_order .= "<table width=\"600\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"background:#fff\">";
$html_email_order .= "	<tr>";
$html_email_order .= " 		<td><table width=\"600\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">";
$html_email_order .= " 			 <tr> ";
$html_email_order .= "    			<td>$Vartable1";
$html_email_order .= "	    			<tr> ";
$html_email_order .= "		 				<td><font face=\"verdana, arial\" size=\"-1\">$Varlogo</font></td>";
$html_email_order .= "					</tr>";
$html_email_order .= "	 			</table></td>";
$html_email_order .= "  		</tr>";
$html_email_order .= "  		<tr> ";
$html_email_order .= "    			<td>$Vartable2 ";
$html_email_order .= "        	<tr> ";
$html_email_order .= "          	<td class=\"main\">$Vartext1</td>";
$html_email_order .= "        	</tr>";
$html_email_order .= "        	<tr height=\"14\"  class=\"detail\"> ";
$html_email_order .= "          	<td height=\"14\">&nbsp;</td>";
$html_email_order .= "        	</tr>";
$html_email_order .= "        	<tr class=\"detail\"> ";
$html_email_order .= "          	<td class=\"main\">$Vartext2</td>";
$html_email_order .= "        	</tr>";
$html_email_order .= "        	<tr height=\"14\"> ";
$html_email_order .= "          	<td height=\"14\">&nbsp;</td>";
$html_email_order .= "        	</tr>";
$html_email_order .= "		</table></td>";
$html_email_order .= "	</tr>";
$html_email_order .= "	<tr>";
$html_email_order .= "   	<td><table width=\"600\"  border=\"0\" cellpadding=\"3\" cellspacing=\"1\" bgcolor=white>";
$html_email_order .= "        	<tr> ";
$html_email_order .= "          	<td class=\"boxmail\" align=\"left\" width=\"100\">Image</td>";
$html_email_order .= "          	<td class=\"boxmail\" align=\"left\" width=\"300\">$VarArticles</td>";
$html_email_order .= "          	<td class=\"boxmail\" align=\"left\" width=\"160\">$VarModele</td>";
$html_email_order .= "          	<td class=\"boxmail\" align=\"center\" width=\"40\">$VarQte</td>";
$html_email_order .= "          	<td class=\"boxmail\" align=\"center\" width=\"40\">Tax</td>";
$html_email_order .= "          	<td class=\"boxmail\" align=\"center\" width=\"80\">Price p. Unit</td>";
$html_email_order .= "          	<td class=\"boxmail\" align=\"right\" width=\"80\">$VarTotal</td>";
$html_email_order .= "        	</tr>";
$m=0;
foreach ($orderarray as $Orderpos){
$modmodel = $Orderpos['Model'];
$modpart = $Orderpos['Modelnr'];
$modqty = $Orderpos['Qty'];
$modtotal = $Orderpos['Price'];
$modunit = $Orderpos['Unitprice'];
$modtax = $Orderpos['Tax'];
$modimage = $Orderpos['Image'];
$html_email_order .= "  		<tr><td width=\"100\" valign=\"middle\" align=\"center\" class=\"boxmailgris".$m."\">$modimage</td>";
$html_email_order .= "  		<td width=\"300\" valign=\"top\" align=\"left\" class=\"boxmailgris".$m."\">$modmodel</td>";
$html_email_order .= "			<td width=\"160\" valign=\"top\" align=\"left\"  class=\"boxmailgris".$m."\">$modpart</td>";
$html_email_order .= "			<td width=\"40\"  valign=\"top\" align=\"center\" class=\"boxmailgris".$m."\">$modqty</td>";
$html_email_order .= "			<td width=\"40\"  valign=\"top\" align=\"center\" class=\"boxmailgris".$m."\">$modtax</td>";
$html_email_order .= "			<td width=\"80\" valign=\"top\" align=\"right\" class=\"boxmailgris".$m."\">$modunit</td>";
$html_email_order .= "			<td width=\"80\" valign=\"top\" align=\"right\" class=\"boxmailgris".$m."\">$modtotal</td></tr>";
$m = $m+1;
if ($m == 2)$m=0;
};
$html_email_order .= "        	<tr height=\"14\"> ";
$html_email_order .= "          	<td height=\"14\" width=\"100\" valign=\"top\" align=\"left\" class=\"tableur\">$Vardetail</td>";
$html_email_order .= "          	<td colspan=\"6\" width=\"700\" valign=\"top\" align=\"right\" class=\"tableur\">$Vartaxe</td>";
$html_email_order .= "        	</tr>";
$html_email_order .= "      </table></td>";
$html_email_order .= "  </tr>";
$html_email_order .= "  <tr>";
$html_email_order .= "      <td><table width=\"600\"  border=\"0\" cellpadding=\"3\" cellspacing=\"1\" bgcolor=white>";
$html_email_order .= "       	<tr> ";
$html_email_order .= "          	<td width=\"300\" class=\"boxmail\">$VarAddresship</td>";
$html_email_order .= "          	<td width=\"300\" class=\"boxmail\">$VarAddressbill</td>";
$html_email_order .= "        	</tr>";
$html_email_order .= "        	<tr> ";
$html_email_order .= "         		<td width=\"300\" valign=\"top\" align=\"left\" class=\"boxmailgris\">$Varshipaddress</td>";
$html_email_order .= "         		<td width=\"300\" valign=\"top\" align=\"left\" class=\"boxmailgris\">$Varadpay</td> ";
$html_email_order .= "        	</tr>";
$html_email_order .= "       </table></td>";
$html_email_order .= "  </tr>";
$html_email_order .= "  <tr>";
$html_email_order .= "		 <td><table width=\"600\"  border=\"0\" cellpadding=\"3\" cellspacing=\"1\" bgcolor=white>";
$html_email_order .= "        	<tr> ";
$html_email_order .= "         		<td class=\"boxmail\">$Varmetodpaye</td>";
$html_email_order .= "        	</tr>";
$html_email_order .= "       	 <tr> ";
$html_email_order .= "          	<td class=\"boxmailgris\">$Varmodpay</td> ";
$html_email_order .= "        	</tr>";
$html_email_order .= "       </table></td>";
$html_email_order .= " 	</tr>";
$html_email_order .= "  <tr>";
$html_email_order .= " 		 <td><table width=\"600\"  border=\"0\" cellpadding=\"3\" cellspacing=\"1\" bgcolor=white>";
$html_email_order .= "       	<tr height=\"14\"> ";
$html_email_order .= "         		<td height=\"14\">&nbsp;</td>";
$html_email_order .= "       	</tr>";
$html_email_order .= "       	<tr class=\"main\"> ";
$html_email_order .= "          	<td class=\"footer\">$Varmailfooter</td> ";
$html_email_order .= "        	</tr>";
$html_email_order .= "      </table></td>";
$html_email_order .= "  </tr>";
$html_email_order .= "</table></td>";
$html_email_order .= "</tr>";
$html_email_order .= "</table>";
$html_email_order .= "</body>";
$html_email_order .= "</html>";
?>
