<?php
/*
  $Id: products_new.php 1739 2007-12-20 00:52:16Z hpdl $
  osCommerce, Open Source E-Commerce Solutions http://www.oscommerce.com
  Copyright (c) 2003 osCommerce
  Released under the GNU General Public License
  960 grid system adapted from Nathan Smith http://960.gs/
  OSCommerce on Grid 960 CSS v2.0 http://www.niora.com/css-oscommerce.php
*/
  require('includes/application_top.php');
 
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="how to paddleboard, get started paddleboarding, introduction to paddling, types of paddle boards" content="text/html; charset=utf-8" />
<title>Kiteboarding Safety</title>
<?php echo $stylesheet; ?>

</head>
 
<?php require(DIR_WS_INCLUDES . 'template-top-info-pages.php'); ?>


<div id="container">

 

   <div id="mainContentwide">
     <h1 class="heading">Safe Kiteboarding Guidelines (As outlined by FKA)</h1>
     <p><img src="images/kite safety.jpg" alt="kite safety" id="descrip-image" /><br />
       <br />
       The following ideas are presented to try to improve kiteboarder and  bystander safety, to reduce complaints and attempt to preserve our  access to ride. These ideas have been taken from the analysis of  hundreds of accidents that have been reported worldwide over many years.  Often accidents might have been avoided if more knowledge and care were  used. <strong>Kiteboarding can be hazardous to the rider and to bystanders,  particularly if practiced without adequate training, safety gear,  knowledge and caution. NOTE: Riders must accept that even if these  guidelines are followed, that accidents, injury and even death may occur  in kiteboarding. </strong>Kites can exert very substantial force with little  to no warning with sudden gusts, lulls followed by gusts, improper line  attachment, mishandling, tangling, malfunction, etc., resulting in  dragging and/or lofting, frequently with insufficient time to  effectively react.  Riders have been lofted in excess of 1700 ft.  downwind and 300 ft. high in strong wind gusts, they have been tangled  by lines and pulled along for miles by looping kites.  And, NO &ldquo;you may  not always be able to just let go or kill the power of the kite,&rdquo; as too  many accidents have established, act early and not during the  emergency. <strong> Your ability to safely and completely depower your kite  and otherwise manage in an emergency will weigh heavily on your  technique, preparation and reliability of your gear. </strong> &quot;Flat&quot; and &quot;C  kites&quot; are mentioned repeatedly in these guidelines, two types of kites  with substantial operation and performance differences.  It is up to the  user to clearly understand what type of kite he is using along with  respective capabilities, limitations, proper setup and operation.  Kite  safety systems can be defeated by lack of knowledge/practice, poor PM or  simple bad luck.<strong> DO NOT RELY upon total depowering</strong> as sometimes it  may not occur, the goal is to avoid the emergency in the first place.<br />
       <br />
Kiteboarders should consider these ideas, area specific guidelines if  applicable along with other prudent and safe practices appropriate for  local conditions.    Cutting corners or picking and choosing safe  kiteboarding practices can seriously reduce the rider&rsquo;s factor of safety  and increase the odds of an accident.<strong> Seek local, competent  knowledge regarding safe local practices as special precautions may be  indicated beyond those discussed here. Safety automatically increases to  some degree once the rider becomes both aware of and takes potential  hazards seriously. By contrast, ignorance and indifference raise the  hazard level substantially and are frequently a factor in avoidable  accidents.</strong> These guidelines have been updated frequently over the  years, so please check the FKA website for the latest version. DO NOT  use old versions of these guidelines as important changes occur with new  knowledge gained over time.</p>
     <p><strong>Some Quick Safety Tips:     </strong></p>
     <ul>
       <li><span mce_style="color: #000000;"><span mce_style="font-family: arial,helvetica,sans-serif;"><u><em><strong>NEVER GO OUT FURTHER THAN YOU CAN SWIM! </strong></em></u></span></span></li>
       <li><span mce_style="color: #000000;"><span mce_style="font-family: arial,helvetica,sans-serif;"><u><em><strong>NEVER DEFLATE YOUR KITE UNLESS ABSOLUTELY NECESSARY!</strong></em></u></span></span></li>
       <li><span mce_style="color: #000000;"><span mce_style="font-family: arial,helvetica,sans-serif;"><u><em><strong>DO NOT RIDE WITHOUT A KITE KNIFE!</strong></em></u></span></span></li>
       <li><span mce_style="color: #000000;"><span mce_style="font-family: arial,helvetica,sans-serif;"><strong><em><u>HELMET AND FLOTATION RECOMMENDED!</u></em></strong></span></span></li>
       <li><span mce_style="color: #000000;"><span mce_style="font-family: arial,helvetica,sans-serif;"><u><em><strong>ONE PUMP USERS: ALWAYS LOCK OFF YOUR STRUTS WHEN SETTING UP!</strong></em></u></span></span></li>
       <li><span mce_style="color: #000000;"><span mce_style="font-family: arial,helvetica,sans-serif;"><em><u><strong>AVOID KITING ALONE!</strong></u></em></span></span></li>
     </ul>
     <p><img src="images/chris crash.jpg" alt="crash"id="descrip-image" /></p>
     <p><strong>GENERAL SAFETY </strong><br />
       <br />
       <strong>1. JUMP TO COMPETENTLY HELP KITEBOARDERS.</strong> Readily help other  riders with launching and landing using reliable agreed upon visual  communications. Be aware of your surroundings and any kiters having  problems.  Do not ignore them but go over and see if they are OK and if  you can help.  Whether you are starting out or are almost a pro, your  help may avoid a serious incident/accident and possible restrictions.  NEVER grab the lines of a flying or powered kite. Get involved with your  local association or club and with area riders to try to preserve  access to kiteboard.<strong> If you see someone putting your access at risk  by poor practices, grab several of your friends and have a friendly talk  with the guy, show some interest followed by your concerns.  Effective  actions may make the difference in avoiding possible injury and related  problems.</strong> Riders are solely responsible for their safety and that of  effected bystanders. If you are new to an area or visiting, seek out  local kiteboarders, shops and/or associations for local guidelines and  tips BEFORE riding. Don&rsquo;t ruin things for the local riders. Always ride  with and stay aware of the status of your kiter buddy.  A  disproportionate quantity of accidents have happened to solo kiters.<br />
       <br />
       2. <strong>GET ADEQUATE QUALITY PRO KITEBOARDING TRAINING.</strong> Kiteboarders,  particularly beginners should seek adequate, quality certified  professional instruction. Not all instruction is of similar quality,  shop wisely for training.  Beginners must avoid crowded areas  particularly as kite control is still being developed. Beginners should  ideally body drag away from shore prior to water starting and should  stay out of guarded restricted beach areas. Be careful in your launch  area selection and be willing to drive and walk a bit further to have  more ideal conditions.<strong> Build your skill and experience carefully in side or side onshore winds (NOT onshore or offshore) ideally less than 18 kts.</strong>.  Riders have been injured for choosing poor launches when far safer  conditions were relatively close by. Be particularly careful in new  conditions and at the START and END of the riding season. Many accidents  occur in these times even among experienced riders. In kiteboarding,  &ldquo;DISTANCE IS YOUR FRIEND,&rdquo; so use it! <br />
       <br />
       3. <strong>KITEBOARD WITHIN YOUR LIMITS.</strong> Know your equipment&rsquo;s  limitations as well as your own. If you aren't 100% healthy, are  intoxicated OR IN DOUBT, DON&rsquo;T FLY! You should be comfortable with  conditions and your gear otherwise, if id doesn't feel &quot;right,&quot; don&rsquo;t  launch and &ldquo;live to fly another day.&rdquo; Always maintain an energy reserve  while out kiteboarding. Hydrate regularly and <strong>wear adequate exposure clothing (wetsuit/dry suit)</strong>,  to deal with unexpected time in the water. Cold water kiteboarding  requires additional critically important precautions compared to warmer  conditions and are beyond the scope of these guidelines. Don&rsquo;t kiteboard  alone or further from shore than you are readily able to swim in from. <br />
       <br />
       4.<strong> USE A RELIABLE EMERGENCY KITE DEPOWERING MECHANISM, QUICK  RELEASES, HELMET, IMPACT VEST, HOOK KNIFE and other reasonable safety  gear.  Properly functioning depowering mechanisms may be more effective  in newer flat kite systems to that used in older C kite designs.</strong> There are MANY new kite and emergency depowering systems on the market  both of new and past designs.  The burden falls upon the rider to pick a  reliable, well maintained system, thoroughly train in its use,  maintenance and to use it prudently.  Many kiteboarding serious  accidents and fatalities involve head injury. A good well fitting and  secured helmet for kiteboarding, MAY aid in reducing injury and improve  the chance of survival in many but not all impacts. A helmet is NO  excuse to kiteboard carelessly. DO NOT freeze holding your flat kite bar  in when you should be sheeting out to effectively depower your kite.   Regularly test and maintain your kite emergency depowering mechanism.  Relying upon manual unhooking alone to release your bar is UNRELIABLE  based upon the accident experience.   The rider needs to understand and  accept that in an emergency,  quick release and depowering mechanism MAY  NOT be accessible or function correctly in the critical seconds of the  emergency. Equipment and activation failures have happened, flat kite  depower has been disabled in emergencies, how much do you want to risk  on this? It is up to the rider to try to <strong>avoid the emergency in the first place </strong>and to aid proper function of the release through regular practice and maintenance. <br />
       <br />
       5. <strong>LAUNCH, RIDE AND LAND WELL AWAY FROM BYSTANDERS.</strong> Give way to  the public on the beach and in the water at ALL TIMES. Be courteous and  polite to bystanders. Complaints have frequently led to bans and  restrictions on kiteboarding in some areas and continue to do so on a  regular basis. NEVER launch, ride, land or walk upwind of nearby  bystanders. Think ahead to protect those around you.  Work to keep a 300  ft. (100 m) buffer zone from bystanders if you can. <br />
       <br />
       6. <strong>BE AWARE OF AND UNDERSTAND THE WEATHER.</strong> Is the forecast and  current weather acceptable, free of pending storm clouds, excessive  gusty winds and hazards? What are real time wind conditions like  upweather, is a cold front or other system bring strong gust spikes?  Timely color radar can sometimes give a clue as to violent storm/gust  potential. Are seas and wind condition within your experience, ability  and appropriate for your gear (check kite manufacturer's wind chart)? <strong>New  kiters should practice in lighter, side or side onshore winds. Onshore  winds have a much higher injury rate even among experienced riders and  should be avoided.</strong> Offshore winds should be avoided in the absence  of a chase boat. If storm clouds are moving in, land and thoroughly  disable your kite well in advance of any change in wind or temperature,  if necessary totally depower your kite by using your kite leash while  still away from shore. Lightning can strike many miles ahead of storm  clouds. Learn about unstable and excessively gusty weather in your area  and work to avoid squalls and storms through TV, radio and Internet  information. <br />
       <br />
       <strong>PREFLIGHT CHECKLIST </strong><br />
       <br />
       1. <strong>USE GOOD LAUNCH AREAS.</strong> Make sure your launch is open, FREE OF  DOWNWIND BYSTANDERS, hard objects, poor or slippery footing, nearby  power lines, buildings and walls etc. within at least 300 ft. (100 m),  and preferably more particularly in higher wind. Too many riders have  slammed into walls, parked cars, trees with better launches not so far  away at all. Some riders have needed in excess of 600 ft. (200 m), to  regain control in violent dragging or loftings in higher winds. Avoid  kiting in areas with gusty winds due to land wind shadow effects. Avoid  kiteboarding near airports and in low flight path areas, complaints have  led to restricted access in some areas. Never fly your kite in the path  of low aircraft in flight, moving your kite low to the water at the  first indication of inbound aircraft. <br />
       <br />
       2. <strong>WHAT SIZE C AND FLAT KITES ARE OTHER RIDERS USING? Check to see  what size kite other kiteboarders are rigging and get their input on  conditions.  Do not directly compare C and Flat kite sizes, there are  critical differences particularly in stronger winds.  Try to select a  kite size for the lower to middle part of the wind range. Do not rig too  large a kite for conditions and carefully consider advice of more  experienced riders. </strong>Failure to act on prudent advice has cost some  riders severe injury and even death. If you don&rsquo;t have a small enough  kite to safely launch, DON&rsquo;T! No one session is worth loss of your life  or injury and extended recovery.  This can and will happen in marginal  conditions over time.<br />
       <br />
       3. <strong>CHECK &amp; REPAIR YOUR GEAR BEFORE YOU FLY. </strong>Check your kite  for tears or leaky bladders. If you have leaky bladders or tears in your  kite, repair them before flying. Check ALL kite, harness, and control  bar lines, webbing, pigtails, bridles, pulleys, the chicken loop,  leaders, bridles, harness for knots, cuts, wear, loose stitching or  abrasion as appropriate. If the line sheathing shows any breaks,  excessive discoloration or knots or pulleys look worn or bind, replace  them. You should plan to replace pigtails, leaders, bridles and pulleys  every 6 months and sooner if necessary based upon condition. Inspect and  test your quick release, pulleys and emergency depowering mechanism.  Frequently, mentally and physically rehearse activate your emergency  depowering mechanism in an imagined emergency situation. Make sure your  flying lines are equal as they will stretch unevenly with use. If they  have knots that can&rsquo;t be easily untied, replace your flight lines. Do  not casually make changes to manufactured equipment. What ever you do  must work reliably in what conditions may come. <br />
       <br />
       4.<strong> AVOID SOLO LAUNCHING.</strong> Solo launching and landing are NOT  recommended and should be avoided particularly in stronger winds. Launch  with a trained assistant, using reliable audible and visual signals. If  solo launching make sure your C kite is properly anchored with a  substantial quantity of sand to avoid premature launch. Flat kites  require different techniques are should not be undertaken without  training or at all in higher winds.  Never use untrained bystanders to  help you launch or land. Riders have been severely injured by making  this easy mistake. Rig your kite for solo launch at the last minute and  launch without delay AFTER CAREFUL PREFLIGHTING as serious accidents  have happened in only minutes during this stage. If you leave the kite  unattended, wrap up your lines, deflate the kite&rsquo;s leading edge and roll  it up. It is best to place the kite in a bag to avoid UV and wind  damage.  Strumming of lines, litter can cause tangles that could cause  an accident on launch.  Solo launching of flat kites may cause tangling  of wing tips and out of control spinning.  Solo launching techniques may  differ for C and Flat kites, KNOW what proper techniques apply to your  kite.<br />
       <br />
       5. <strong>CROSSED KITE LINES CAN WRECK YOUR DAY. </strong>Launching with crossed  or snagged lines has maimed quite a few kiteboarders as the kite tends  to fly up at very high speed, dragging or lofting the rider into a  nearby hard objects faster than they can react. Walk down your lines and  examine them carefully. Pick your bar up and carefully look down the  lines for twists, tangles or snags that could cause the kite to be  dangerously uncontrollable. While you are holding your bar up look down  the lines, shake your bar to make sure the center lines are connected to  the leading edge of the kite. Your assistant should check the lines  from his end as well.  Be particularly careful, slow and methodical in  high winds. Multiple, careful preflighting in higher winds is strongly  advised as lines can tangle on their own through strumming in the wind.  &quot;Kook Proof&quot; connectors are standard on most new kites.    Do not use  snaps or connectors that can readily open and catch lines under tension.   Do not use side release snap shackles for kitesurfing in ANY  application.  Be careful NOT to attach your kite leash upside down to  where you can't activate it.<br />
       <br />
       <strong>LAUNCHING AND GETTING UNDERWAY </strong><br />
       <br />
       1.<strong> LAUNCH &amp; LAND YOUR <em>C KITE UNHOOKED</em> WITH A GOOD BUFFER ZONE WITH C KITE. BE PREPARED TO TOTALLY DEPOWER YOUR FLAT KITE BY PUSHING YOUR BAR OUT ALL THE WAY ON YOUR <em>HOOKED IN FLAT KITE</em>.</strong> Avoid hooking in or connecting with your quick release, while onshore  or near hard objects WITH C KITES, practice LAUNCHING AND LANDING  &quot;UNHOOKED&quot; or not connected to your chicken loop. <strong>Pull in your trim  strap or rope entirely or to a point that will allow stable kite flight  with existing wind conditions, to properly depower the kite before  launching and so that you can readily hold the bar and release it if  necessary with C kites. </strong>Always maintain minimum clear downwind  buffer zones, particularly while flying unhooked. Physically and  mentally rehearse managing emergency situations including just &quot;letting  go&quot; of your bar. Connect to your quick release once you are well  offshore with C kites. KNOW where your kite leash attachment Quick  Release is at ALL TIMES, make sure it works with regular practice.  If a  flat kite goes into a spin releasing the kite entirely may be your only  option. <br />
       <br />
       2. <strong>KEEP IT LOW &amp; GO!</strong> to try to avoid lofting or involuntary  lifting unless directed otherwise by good, proven local practice in  appropriate conditions.  This approach may not be appropriate in areas  with poor traction due to slippery footing, hard objects between the  kiter and the water.   In general, Do not bring your kite very high up  or to the vertical, within 300 ft. (100 m) of shore or any hard object  at most launch areas. Never launch, fly or land upwind and close to the  shore or hard objects or stand on the beach for extended with your kite  in the air. This careless practice has killed and maimed riders. This  practice MAY reduce the chance of lofting but may also promote dragging  and serious injury or death in gusty/strong wind conditions. So, if you  are dragged be ready to totally depower instantly, i.e. using your kite  leash or effectively sheeting out your flat kite control bar and ideally  before the dragging starts in the first place. HAZARD AVOIDANCE IS THE  KEY along with rapid preemptive, rehearsed actions.  Do not fly your  kite near vertical or sloped surfaces that can cause uplift and sudden  dragging/lofting (walls, buildings, hills, tree lines, etc,).  Launch in  the appropriate part of the wind window to avoid &ldquo;hot&rdquo; or over-powered  downwind launches. Make sure that there are no bystanders within your  downwind buffer zone or close by in general. <br />
       <br />
       3. <strong>GET OFFSHORE AND STAY THERE.</strong> Go offshore at least 300 ft. (100  M) WITHOUT DELAY after launch. Stay beyond 300 ft. until time to come  in. If there are substantial waves where you need to put on your board  consider body dragging outside the breaker zone first. The fun is  offshore, danger to the rider &amp; bystanders is elevated near shore  where most of the hard stuff is located. Riders have been killed and  severely injured by impacting water at speed as a result of strong wind  gusts. <br />
       <br />
       4. <strong>YIELD THE RIGHT OF WAY. </strong>Yield the right of way to all others  in the water. Riders must yield to others when jumping, to anyone on  your right hand side and to launching riders. When in doubt, STOP.  Kiteboarders should not jump within a buffer zone of at least two  hundred feet (60 m) of others and objects that are downwind. Always be  aware of the position of your lines relative to others, line cuts can be  severe and tangled lines with another kite, deadly. <br />
       <br />
       5. <strong>BOARD LEASHES ARE DANGEROUS.</strong> All kiteboarders are encouraged  to master body dragging for board recovery. Use of a board leash is  dangerous and is generally discouraged due to the hazards of board  rebound or wave driven impact. Injuries have happened with both fixed  length and reel leashes. Wearing a helmet and impact vest is always  advised but may not provide adequate projection against board impact as  the boards can and have violently hit any part of the rider and have  penetrated helmets. If there is risk of your loose board hitting  bathers, find another launch. Some areas with adverse currents,  hypothermic or other special conditions may dictate the use of reel  leashes.  Riders choosing to kite in such conditions must accept the  higher likelihood of injury due to board leash use.<br />
       <br />
       6. <strong>DON&rsquo;T GET LOFTED! </strong>Lofting or involuntarily lifting is one of  the greatest hazards of kiteboarding. The majority of loftings appear to  have been readily avoidable as well.  Avoiding unstable weather,  keeping your kite low and getting offshore without delay are only a few  of the measures necessary to avoid this threat.<strong> If despite all  precautions you are dragged or lofted a short distance AND have time to  react, depower your kite as soon as you start to pause. You will likely  be dulled by shock so mentally rehearse totally depowering sheeting your  flat kite out or using your kite leash immediately under such  circumstances. After initial impact you may not have sufficient  awareness or even be conscious to act so when in doubt ACT EARLY, don't  wait.  Total depowering by sheeting out your flat kite or using your  kite leash on C kites, ideally should occur before you are lofted, still  offshore and away from hard objects.</strong> Multiple gusts can hit over a  short period and you may be lofted a second or third time, lulls can  stall your kite before gusts relaunch it so ACT to totally depower your  kite as soon as you can. DO NOT ASSUME that you will have a lull between  loftings, sometimes you do and sometimes you don&rsquo;t. If you are air born  over land, it is uncertain how and if you will come out of things.  Focus on controlling your kite with small control inputs to avoid  stalling the kite. Some have advised keeping the kite overhead AFTER you  are lofted and to try to gently steer towards the least hazardous are  to impact. Other riders have said that reversing direction or  transitioning after lofting has helped to reduce forward speed. It would  be wise to accept and plan for the fact that YOU CAN BE LOFTED AT  ANYTIME you are connected to a kite. <br />
       <br />
       7.  <strong>AVOID LINE TANGLES AT ALL COSTS</strong>.  If you stall your kite or if it is  hit by a lull, you may receive a shower of line or you may become  tangled by lines in the water without your knowledge.  If your kite is  on the water and you are in waves, an adverse current or aren't paying  attention you can be tangled below water and not even realize it.  If  the kite powers up and relaunches, is caught be a wave or is propelled  by current you could be badly cut, drowned or otherwise seriously hurt.     If your kite lines are tangled by a submerged object like a rock or  pile fouling and the kite is loaded up by current or waves you may be  held underwater.  Strive to avoid tangles and carry knives(s) in good  locations to increase the odds of being able to cut free. If you are  tangled by lines and your kite relaunches it may loop out of control and  disable your ability to depower or even release the kite entirely.   Sometimes, cutting free is not feasible leaving the rider in a very bad  way.  Anticipate the emergency and work to AVOID it.<br />
       <br />
       <strong>LANDING</strong><br />
       <br />
       1. <strong>USE ASSISTED LANDINGS BUT . . .SOLO DEPOWER YOUR KITE IMMEDIATELY IF NECESSARY!</strong> Solo depowering means to fully depower your kite by sheeting out your  Flat Kite or dropping your control bar to activate your kite leash on C  kites.  Approach the shore slowly with caution. Keep your kite low, to  try avoid lofting in many circumstances. Take care to avoid causing an  accidental jump in well powered conditions while approaching the shore.  Arrange for assisted landings at least 300 ft. (100 m) from bystanders,  power lines, vertical surfaces, etc.. NEVER use non-kiteboarders for  assisted launches or landings, as use of bystanders has resulted in  severe rider injuries. Use mutually understood hand and voice signals to  improve launch and landing safety. Riders have been killed standing  around looking for an assisted landing when gusts have hit. IF IN ANY  DOUBT, TOTALLY DEPOWER YOUR KITE  even if you are still offshore. ALL  riders should be comfortable with depowering their kite using their  leash immediately even in deep water and swimming in to avoid being  lofted or dragged in sudden gusting winds. MAKE SURE you know how to and  have PRACTICED self-rescue using your kite as a sail.  ALL kiters  should possess this skill through practice.<br />
       <br />
       2. <strong>PROPERLY STOW YOUR GEAR. </strong>Properly anchor (or ideally deflate  your leading edge and roll up your kite), disconnect and wind up your  kite lines. Do not allow your kite to be accidentally launched. Kites  should be placed in a safe area well out of bystander and vehicular  traffic.<br />
       <br />
     <h1><a href="http://www.jupiterkiteboarding.com/store/frequently-asked-questions-i-57.html">Next: Frequently Asked Questions</a></h1>
     </h1>
   </div>
</div>


<?php
  

require(DIR_WS_INCLUDES . 'template-bottom.php');
require(DIR_WS_INCLUDES . 'application_bottom.php'); 
?>