<?php
$html_email_orders = "<html>";
$html_email_orders .= "<head>";
$html_email_orders .= "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"> ";
$html_email_orders .= "$Varhttp ";
$html_email_orders .= "$Varstyle ";
$html_email_orders .= "</head>";
$html_email_orders .= "<body>";
$html_email_orders .= "<table border=\"0\" cellpadding=\"2\" cellspacing=\"2\" class=\"emailbody\">";
$html_email_orders .= "	<tr class=\"emailbody\">";
$html_email_orders .= " 		<td class=\"emailbody\"><table width=\"600\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">";
$html_email_orders .= " 			 <tr> ";
$html_email_orders .= "    			<td>$Vartable1";
$html_email_orders .= "	    			<tr> ";
$html_email_orders .= "		 				<td>$Varlogo</td>";
$html_email_orders .= "					</tr>";
$html_email_orders .= "	 			</table></td>";
$html_email_orders .= "  		</tr>";
$html_email_orders .= "  		<tr> ";
$html_email_orders .= "    			<td>$Vartable2 ";
$html_email_orders .= "        	<tr> ";
$html_email_orders .= "          	<td class=\"main\">$Vartext1</td>";
$html_email_orders .= "        	</tr>";
$html_email_orders .= "        	<tr height=\"14\"  class=\"main\"> ";
$html_email_orders .= "          	<td height=\"14\">&nbsp;</td>";
$html_email_orders .= "        	</tr>";
$html_email_orders .= "        	<tr class=\"main\"> ";
$html_email_orders .= "          	<td class=\"main\">$Vartext2</td>";
$html_email_orders .= "        	</tr>";
$html_email_orders .= "        	<tr height=\"14\"> ";
$html_email_orders .= "          	<td height=\"14\">&nbsp;</td>";
$html_email_orders .= "        	</tr>";
$html_email_orders .= "			<tr>";
$html_email_orders .= "				<td height=\"14\" class=\"main\">$Varbody</td>";
$html_email_orders .= "			</tr>";
$html_email_orders .= "        	<tr height=\"14\"> ";
$html_email_orders .= "          	<td height=\"14\">&nbsp;</td>";
$html_email_orders .= "        	</tr>";
$html_email_orders .= "        	<tr height=\"14\"> ";
$html_email_orders .= "          	<td height=\"14\"><font face=\"verdana, arial\" size=\"-1\">$Varmailfooter</font></td>";
$html_email_orders .= "        	</tr>";
$html_email_orders .= "		</table>";
$html_email_orders .= "		</table>";
?>