<?php

require('includes/application_top.php');

$list = [
    'Kite Fix GluFix 1oz Tube',
    'NPX Fury Boardshorts',
    'NPX Wasted Boardshorts',
    'Ez Kine El Capo 10" Stand Up Paddleboard Fin',
    'Ez-Kine Hook 9" Stand Up Paddleboard Fin',
    'Ninja Weedles Paddleboard Race Fin by Larry Allison - Red',
    'Pro Fitness Paddleboard Race Fin by Larry Allison',
    'Stealth Paddleboard Race Fin by Larry Allison',
    'Rainbow 9" Fin',
    'RFC Seeker 12" Stand Up Paddleboard Fin',
    'RFC Surfer 10" Stand Up Paddleboard Fin',
    'Dakine SUP Paddleboard Bag 10\'6 x 31" Day Bag',
    'FixMyKite Micro Hook Braiding Tool',
    'RFC Thruster FCS 3 Fin Set Rainbow Fin Co. - Plastic',
    'RFC Thruster FCS 3 Fin Set Rainbow Fin Co. - R5 Fiberglass',
    'Pro Teck Power Flex 4" Performance FCS Side Fins',
    'RFC Explorer 8" SUP Paddleboard Fin',
    'Gladiator Elite Paddleboard Race Fin by Larry Allison',
    'Dakine Heavy Duty L/S - L White',
    'Dakine Heavy Duty L/S - L Black',
    'Dakine Heavy Duty L/S - XXL White',
    'Dakine Heavy Duty L/S - M White',
    'Dakine Slider Bag - 155 x 44',
    'Dakine Storm Neo-Insulator L/S - L',
    'Dakine Storm Neo-Insulator S/S - L',
    'Dakine Storm Neo-Insulator S/S - S',
    'Dakine 6\'0" Knit Surf Bag Thruster',
    'Dakine Kalani Pro Traction Pad',
    'Dakine Daylight Deluxe Thruster Surf Board Bag - 5\'8" Charcoal',
    'Dakine Daylight Deluxe Thruster Surf Board Bag - 5\'4" Charcoal',
    'North Replacement Depower Line & Bolt - 2014/2013 with allen key',
    'Futures Byron Kurt Race Fin',
    'Futures Karen Wrenn',
    'Powerline Sports Q-PowerLine Pro 600 lb 500 ft Spectra LIne - White',
    'Powerline Sports Q-PowerLine Pro 600 lb 500 ft Spectra LIne - Grey',
    'Larry Allison Gladiator Hybrid Fin - Blue',
    'Larry Allison Gladiator Hybrid Fin - Red',
    'Fix My Kite Pre Sleeving Kit',
    'Kids Kite',
    'House Flag Asst. Large - Regular',
    'House Flag Asst. Large - Burlap',
    'House Flag Asst. Large - Assorted Large',
    'NP Mission 2mm Top - XS',
    'Dakine Riddler Traction Pad - Camo',
    'Dakine Riddler Traction Pad - Pink/ Black',
    'Dakine Riddler Traction Pad - Red/ Black',
    'Dakine Hypno Traction Pad',
    'Dakine Skull Traction Pad - Pink/ Black',
    'Dakine Skull Traction Pad - White/Black',
    'Dakine Studio Traction Pad',
    'Xtrak Woodrow',
    'Dakine Machado Traction Pad',
    'Dakine Rizal Traction Pad',
    'Xtrak Agent X Traction Pad',
    'FCS Dayrunner Longboard',
    'QFR Fin Release',
    'Windsock',
    'Dakine Heavy Duty S/S - S Pacific',
    'Dakine Heavy Duty S/S - L Pacific',
    'Dakine Performance L/S - S Black',
    'Dakine Performance S/S',
    'FCS Explorer Longboard Bag',
    'NP Womens Neo  Shorts - M',
    'NP Womens Neo  Shorts - L',
    'NP Womens Neo  Shorts - XS',
    'NP Womens Neo  Shorts - S',
    'NP Women\'s SUP Jacket - XS',
    'FCS T-3 Traction Pad - Black / Charcoal',
    'FCS T-3 Traction Pad - Charcoal Camo',
    'FCS T-3 Traction Pad - Seared',
    'FCS T-3 Traction Pad - Black',
    'FCS T-5 Traction Pad - Blue',
    'Dakine Knit Surf Bag 6\'6',
    'Turq Swim Briefs - M Blue',
    'Turq Swim Briefs - XL Grey',
    'Turq Swim Briefs - XS Black',
    'Turq Swim Briefs - L Grey',
    'Turq Swim Briefs - L Black',
    'Turq Swim Briefs - S Black',
    'Turq Swim Briefs - XL Black',
    'Dakine Beach Stripe Traction Pad - Rasta',
    'Dakine Beach Stripe Traction Pad - Navy',
    'RFC Pro Core Quad Fins',
    'RFC Rusty Flex 7" Fin - Black/Red',
    'Dakine Waterwoman Hoodie - S',
    'FCS Candice Appleby Race Fin',
    'FCS Premium Bungy Lock Downs',
    'FCS 9\' Big Wave Ankle Surf Leash',
    'FCS Adjustable SUP Race Comp Ankle Leash',
    'FCS Adjustable SUP Race Comp Calf Leash',
    'Dakine Slider Wedge - 185',
    'Ion Twintip Bag Core - 137 x 43',
    'Mystic Gearbox',
    'Cabrinha Replacement Kiteboard Fins X4 - 30mm',
    'Cobian Men\'s Draino - 10 Cement',
    'FCS II Performer PC Carbon Tri Set - Medium',
    'FCS II Performer PC Carbon Tri Set - Large',
    'KanuLock Paddleboarding Locking Straps - 13\' Yellow',
    'Green Tractor Spinner - 24"',
    'Small Flame Motorcycle Spinner',
    'University Of Florida 28\'x40\' Banner Flag',
    'University Of Florida 3\'x5\' Flag',
    'Frog Large Whirligig',
    'Party Cups Large Whirligig',
    'Red Roses Windsock',
    'Tuxedo Cat Bike Spinner - 20"',
    'Fin Box Cleat',
    'Ultimate Frisbee Disc',
    'Blue Exotic Bird Kite',
    'Rainbow Bird Kite',
    'Ron Gibian Collections Kite',
    '36" Box Kite',
    'Roto S Single Line Box Kite',
    'Stealth Attack 3D Jet',
    'Diamond Single Line Kite - Hedgehog',
    'Diamond Single Line Kite - Jawbreaker',
    'Diamond Single Line Kite - Ruby',
    'Diamond Single Line Kite - LOL',
    'Diamond Single Line Kite - Monkey',
    'Diamond Single Line Kite - Purple Haze',
    'Diamond Single Line Kite - Tropical Fish',
    'Team Series 6\'7 Burgundy',
    'Airtime Slingshot OEM One Pump Valve',
    'Tulip Bouquet Windsock',
    'GoBag Dry Bag Minnow',
    'RSPro Hibiscus - Clear Orange',
    'RSPro Hibiscus - Clear',
    'RSPro Hibiscus - Clear Green',
    'State of Florida Flag - 2\' x 3\'',
    'ION Single Twintip Boardbag - 130',
    'Ion Multipiece Traction Pad - Grey/Orange',
    'Ion Multipiece Traction Pad - Muse 2 Piece',
    'Ion Multipiece Traction Pad - Muse 3 Piece',
    'Ion Multipiece Traction Pad - Stripe 2 Piece',
    'Dakine Offshore L/S - XXL White',
    'Dakine Offshore L/S - S Grey',
    'Dakine Watermans S/S',
    'Mystic Block Quick Dry S/S',
    'Mystic Force Quick Dry S/S',
    'Dakine Polypro L/S - L',
    'Dakine Polypro L/S - S',
    'Dakine Surf Shirt S/S',
    'Cobian Women\'s Nias Bounce - 9 White',
    'Fin Screw and Channel Plate',
    'LA Team Race Fins by Larry Allison - Red',
    'Larry Allison Gladiator Pro Click It',
    'Larry Allison Ninja Click It',
    'Larry Allison Ninja Reg',
    'Larry Allison Stealth Click It',
    'Monarch Triple Spinner',
    '2015 Liquid Force Core Helmet - XS Black',
    '2015 Liquid Force Core Helmet - S Black',
    '12" x 18" Pirate Flags - Fish Or Cut Bait',
    "3' x 5' Pirate Flags - The Beatings Will Cont.",
    "3' x 5' Pirate Flags - Don't Tread - Pirate",
    "2-Sided 13\"x18\" Florida Gators Garden Flag",
    "28\"x44\" Michigan State Univ.",
    'Sex Wax Tropic Wax 6 Pack',
    'Ozone kite compression strap',
    'Zephyr Stunt Kite - Inferno',
    'Pineapple Greeting Burlap Door Hanger',
    'Full Foot Rubber Fin - 5-7',
    'Full Foot Rubber Fin - 9-11',
    'Full Foot Rubber Fin - 7-9',
    'Full Foot Rubber Fin - 11-13',
    'Whirly Wing Spinner - Hummingbird',
    '12" x 18" Coast Guard Nylon Flag',
    'Local Unisex Performance Hogfish Shirt LS - XXL',
    'Local Unisex Performance Marlin LS - L',
    'Ozone Replacement Fly Lines - 4 x 20m 500kg/300kg',
    'Ozone Replacement Fly Lines - 4 x 25m 500kg/300kg',
    'Ozone Replacement Fly Lines - Pro Race 4 x 15m 300kg/200kg',
    'Liquid Force Divison Boardshorts - 30"',
    'Liquid Force Robinson',
    'Dakine Womens Flow Snug Fit Rash Guard - S Black',
    'Dakine Womens Flow Snug Fit Rash Guard - M Pastel Current',
    'Tecmo Deluxe Spinner Set',
    'Tecmo Large Set',
    'Liquid Force Hinge CGA',
    'HSA Bow Tow Rope',
    'HSA Quick Release Assembly',
    'Parrot metal art - Red & Blue - Pair of Parrots 13"',
    'Pineapple metal art - 17"',
    'Sea Turtle Metal Art - S Blue',
    'Sea Turtle Metal Art - S Green',
    'Sea Turtle Metal Art - S Yellow',
    'Sea Turtle Metal Art - S Heart Shape',
    'Sea Turtle Metal Art - Lg Heart Shap',
    'Surfboard Metal Art - 54"',
    'Lighthouse Metal Art - Turtle',
    'Lighthouse Metal Art - Tropical',
    'Seahorse Metal Art - w/ Anchor',
    'Spotted Eagle Ray Metal Art - 18"',
    'Welcome signs metal art - Pineapple',
    'Welcome signs metal art - Sun',
    'Welcome signs metal art - Seahorse',
    'Dakine Waterwoman',
    'Local Brand Vinyl Decal - 16"',
    'Local Brand Vinyl Decal - 10"',
    'Local Brand Vinyl Decal - 20"',
    'Pumpkins this way',
    'Dakine Flow Loose Fit LSL - Bay Islands',
    'Dakine Flow Loose Fit LSL - Bay Islands',
    'Dakine Flow Loose Fit LSL - Bay Islands',
    'Dakine Flow Loose Fit LSL - Bay Islands',
    'Dakine Flow Loose Fit LSL - S Black',
    'Dakine Flow Loose Fit LSL - S Lunar Rocks',
    'Dakine Flow Loose Fit LSL - XS Black',
    'Christian Flag 2 x 3',
    'Wood Magnet - Sea Turtle',
    'Croakies Float Kit',
    'Croakies Stealth Floater Yellow',
    'Croakies XL Black',
    'FCS II Performer Neo Glass Tri-Set - Large',
    'FCS II Performer Neo Glass Tri-Set - Medium',
    'Croakies Arc Endless XL/XXL Black 16"',
    'Turkey Spinner',
    'Wooden Turtle Wind Chimes',
    'Cobian Beacon - 8 Chocolate',
    'Dakine Kainui Leash - 6\' x 5/16"',
    'Dakine Longboard Series 12\' Calf Leash',
    'Dakine SUP Calf 10\' x 5/16" Leash',
    '12"x18"  Cocktail Time Flag',
    '3\'x5\' Happy Chanukah Flag w/ Grommets',
    '3\'x5\' Happy Holidays Flag w/ Grommets',
    '3\'x5\' Roof Top Santa Flag w/ Grommets',
    '3\'x5\' Season\'s Geetings Flag w Grommets',
    '3\'x5\' Sleigh Flag w/ Grommets',
    'American Flags - 2.5\' x 4\' Sewn and Embroidered',
    'American Flags - 12x18 USA',
    'NP Hybrid Walk Shorts',
    'NP Surf Board Bag 6\' 6"',
    'Ozone T-Shirt',
    'Ozone T-shirt Brand',
    'Macaw Kite',
    'FCS Dave Kalama 9"',
    'FCS II Danny Ching 9"',
    '2015 -2019 Cabrinha Recoil CAS Replacement',
    'FCS II Connect GF - 10"',
    'FCS II Flow PG - 8" CLear',
    'FCS II Flow PG - 9" Clear',
    'FCS II Flow PG - 10" Clear',
    'FCS II Pivot PG - 8" Purple',
    'Road Biker - Man & Woman - woman 35"',
    'Road Biker - Man & Woman - Woman 22"',
    'Womens\' Flow Loose Fit - M Solstice',
    'Womens\' Flow Loose Fit - XS Furrow',
    'Womens\' Flow Loose Fit - XS Solstice',
    'Womens\' Flow Loose Fit - S Solstice',
    'Cobian women\'s Hanalei - 6 Black',
    'Cobian women\'s Hanalei - 6 Coral',
    "Cobian Women's Leucadia - 8 natural",
    "Cobian Women's Fiesta Skinny Bounce - 7 Tan",
    "Cobian Women's Fiesta Skinny Bounce - 7 sunset",
    "Cobian Women's Fiesta Skinny Bounce - 6 sunset",
    "NP Women's Ripple Board Shorts - XS",
    "NP Women's Ripple Board Shorts - S",
    "NP Women's Ripple Board Shorts - L",
    "Inner Visions T-shirt Tie Dye",
    "Dakine Boy Toddler Snug Fit L/S - 3T",
    "Dakine Boy Toddler Snug Fit L/S - 4T",
    "Dakine Boy Toddler Snug Fit L/S - Hoodie 4T",
    "Dakine Women's Shaka Tech Tank - Large Heather Black",
    "North Boardshorts - L Iron Gate",
    "North Boardshorts - L Process Blue",
    "North Tee SS Team - M",
    "Endless Summer Spinner",
    "Local KISS Tank - S",
    "FCS II Filipe Toledo PC Tri Fin - L Black",
    "FCS II Matt Biolos PC Tri Quad Fin Set - Blue",
    "FCS II Mick Fanning Large Tri-Fin - Performance Core Black/Olive",
    "FCS II Mick Fanning Large Tri-Fin - Neo Carbon Black/Charcoal",
    "Ion Handlepass Leash 2.0 Comp - 110/170 Yellow",
    "Dancing Mermaid Cutouts Metal Art - S",
    "2021 Liquid Force Watson CGA",
    "David Ti Series House Flag - Hydra Rainbow",
    "LOCAL Horizon Lilac - S",
    "Classic Cruiser 30\" Bicycle Spinner",
    "Surfing Penguin Garden Charm",
    "North Tee SS Green - XL",
    "Straightline 60' Tube Rope - 680lb White",
    "Pirate Parrot Spinner",
    "Pirate Parrot Spinner",
    "Binka Hoodie - Palm Tree",
    "Binka Hoodie - Seahorse",
    "Binka Tank - Give Love",
    "Binka Tank - Anchor",
    "Binka Tank - Yin Yang Koi",
    "2021 Liquid Force Happy Hour Comp - M Agua/Heather",
    "2022 Liquid Force Focus Wakeskate - 44",
    "Metal Art - Drinks - Pineapple Rum",
    "Mystic Golfbag 150 cm",
    "Mystic Majestic Stubby - 5'6",
    "Night Garden Solar Mobile",
    "Glass Wind Chimes - Sand Dollar",
    "Glass Wind Chimes - Starfish",
    "Glass Wind Chimes - Shell Trio",
    "Pineapple Wind Chimes",
    "Duotone Team Traction Pad Front - Red/Blue",
    "Costa Beachside Shirt - Military Green",
    "Costa Ocearch Fin - XL White",
    "Costa Ocearch Fin - XL Charcoal",
    "Costa Ocearch Fin - M Charcoal",
    "Costa Ocearch Fin - L White",
    "Costa Ocearch Fin - M White",
    "Costa Ocearch Fin - S Charcoal",
    "Costa Ocearch Marine - L Black",
    "Costa Ocearch Marine - M Sky",
    "Costa Ocearch Marine - M Black",
    "Costa Ocearch Marine - XL Black",
    "Costa Ocearch Marine - XL Sky",
    "Costa Pride - XXL Tan",
    "Costa Pride - XL Tan",
    "Costa Pride - XL Navy L/S",
    "Costa Pride - L Tan",
    "Costa Pride - XXL Navy L/S",
    "Cellular Kite",
    "Spectra Line Extractor Winder",
    "Cactus Metal Art - M",
    "2018 Mystic Concrete Tee",
    "Mexico Flag 2 x 3",
    "UK Flag 2 x 3",
    "Local Dawn Patrol",
    "Dragon Bike Spinner",
    "2019 Dakine T-Shirt Long Sleeve - XX Large",
    "2019 Dakine T-Shirt Short Sleeve - XX Large",
    "2019 Dakine T-Shirt Short Sleeve - X Large",
    "2019 Dakine T-Shirt Short Sleeve - Large",
    "2019 Dakine T-Shirt Short Sleeve - Medium",
    "2019 Dakine T-Shirt Short Sleeve - Small",
    "Dakine Kokio Hybrid Shorts - 34\"",
    "Dakine Heavy Duty Snug Fit S/S - XXL White",
    "Dakine Heavy Duty Snug Fit S/S - XL White",
    "Dakine Heavy Duty Snug Fit S/S - L Carbon",
    "Dakine Inlet Loose Fit S/S - L Carbon",
    "Dakine Inlet Loose Fit S/S - S Carbon",
    "Dakine Inlet Loose Fit S/S - M Carbon",
    "Dakine Inlet Loose Fit S/S - XXL Carbon",
    "Dakine Inlet Loose Fit S/S - XL White",
    "Dakine Intermission Loose Fit S/S - M Static",
    "Dakine Intermission Loose Fit S/S - XL Static",
    "Womens Vamp Neo Top - S Peach",
    "Beatnik Trading Surfboard Bag & Hammock",
    "Regal Chimes - Octopus",
    "Regal Mermaid Wall Decor",
    "Costa Del Mar Techsail Rashguard - Small",
    "Costa Del Mar Techsail Rashguard - Large",
    "Stormchaser Neo Jacket - XL Neil Pride",
    "Cabrinha W-L/S Lycra - XS",
    "FCS SUP Essentials Leash",
    "Sport Pickup Truck Spinner",
    "VW Spinners 26\" - 26\" VW Red Convertible",
    "Santa on a Chopper Spinner 28\"",
    "Valentine's Day Windsock",
    "Warm Tropical Koi Windsock",
    "Winter Wonderland Seasons Greetings Windsock",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil Flat Tail Wing - 18''",
    "GoFoil Carbon Mast - 60cm/23.62",
    "Liquid Force Kids Wipeout Helmet",
    "Liquid Force Enigma Comp",
    "2021 Liquid Force Hinge CGA - S Blue/Grey",
    "Finjak Single Fins In a Flash",
    "2020 Watson Comp - L Black",
    "2021 Liquid Force Flash Helmet - L Woodstock",
    "2021 Liquid Force Flash Helmet - M Mint",
    "2021 Liquid Force Plush - 4-7",
    "2020 Mystic Flight Bag",
    "ION Muse Neo Zip Top 1.5 DL Fleece Lined - S Black",
    "ION Muse Neo Zip Top 1.5 DL Fleece Lined - M Black",
    "ION Muse Neo Zip Top 1.5 DL Fleece Lined - XS Black Capsule",
    "ION Muse Neo Zip Top 1.5 DL Fleece Lined - S Black Capsule",
    "Ion Wetshirt Hood Men LS - S",
    "Surfboard Pads ION Maiden 3pcs",
    "Wetshirt Men LS",
    "Cobian Womens Shimmer - pearl 8",
    "Cobian Womens Shimmer - pewter 9",
    "Cobian Womens Shimmer - pearl 7",
    "2020 Strike Select Semidry 5/4 BZ DL - XXL",
    "2020 Strike Select Semidry 5/4 BZ DL - XL",
    "Ion Neo Top Men 0.5 SS - S",
    "ION Windsurf / Foilboard CORE Boardbag - 255x85 - L",
    "Cobians Men A.R.V.II - 10 Chocolate",
    "Cobians Men A.R.V.II - 8 Chocolate",
    "Cobians Men floater - 8 Cement",
    "86\" Rainbow Owl Bird Kite",
    "Black Bear Bicycle Spinner",
    "Turtle Car Spinner",
    "GoFoil and Standard Deep Tuttle Drop-in Plate Adapter",
    "Shamrocks 40 in",
    "Spiral Column 40 in",
    "Sunflowers 40\"",
    "Unicorn Party 40 in",
    "Welcome Pine",
    "Cobian Women Bethany Tradewinds - 7 Seafoam",
    "Cobian Women Bethany Tradewinds - 9 Seafoam",
    "Cobian Women Bethany Tradewinds - 6 Black",
    "Cobian Women Bethany Tradewinds - 8 Black",
    "Storm Chaser Hoodie - XL",
    "Storm Chaser Hoodie - L",
    "Surge LiP Sunglasses - Matt Black-Black/Series ML Red",
    "Typhoon LiP Sunglasses - Black / Brown",
    "Lift Surf V2 Series Back Wings",
    "Ladybug Bike Spinner 20\" - Large",
    "FCS II Performer Thruster - Performance Core Teal L",
    "FCS II Performer Thruster - Neo Glass Teal L",
    "Mystic Car Seat Cover - Single",
    "Osprey Sport Kite - Rainbow Raptor",
    "2021 Ocean Rodeo Roam A-Series",
    "2021 Cabrinha Fusion Front X-Series Foil Wings - 160",
    "2021 Cabrinha Fusion X-Series Stabilizer Rear Wing - 220 Rr",
    "2021 F-One Bandit S2 - 7m Papaya",
    "2021 Gofoil Flip Tip Tail Wing - 12.5''",
    "2021 Gofoil Flip Tip Tail Wing - 17.5''",
    "Banner Flags - Jolly Roger 8.5 ft Feather",
    "Banner Flags - Parrot Paradise 8.5 ft Feather",
    "Banner Flags - Open 8.5 ft Block",
    "Banner Flags - Open 8.5 ft Circle",
    "Half Strap 2.0 - One Size",
    "2021 Liquid Force Idol 6x Bindings - 11-12",
    "Great Blue Heron 30\" Bird Spinner",
    "Wavy Rainbow 40in Box kite",
    "2020 GoFoil GL Series Front Wings - 100",
    "2020 GoFoil GL Series Front Wings - 80",
    "2020 GoFoil GL Series Front Wings - 140",
    "2020 GoFoil GL Series Front Wings - 120",
    "Airush Lithium V12 - 9m Teal",
    "Airush Lithium V12 - 10m Teal",
    "Airush Ultra V4 - 6m Slate",
    "Airush Ultra V4 - 10m Slate",
    "2021 Liquid Force Hinge Classic CGA",
    "Softech Mason Twin Surfboard - 5'10''",
    "Mystic Bolt Long Sleeve T-Shirt - XXL Black",
    "Mystic Bolt Long Sleeve T-Shirt - L Black",
    "Mystic Sundowner T-Shirt - L White",
    "Mystic X The Heat T-Shirt - M Black",
    "Mystic X The Heat T-Shirt - L Black",
    "12\"x18\" Nylon Flags - new york",
    "12\"x18\" Nylon Flags - australia",
    "Zinka SPF 50+ Colored Face Stick - Clear",
    "Zinka SPF 50+ Colored Face Stick - Blue",
    "Zinka SPF 50+ Colored Face Stick - Tan",
    "Mystic Lowe Sweatshirt - M Black",
    "Mystic Lowe T-shirt - L White",
    "Mystic Lowe T-shirt - L Black",
    "Mystic Lowe T-shirt - XL Black",
    "Mystic Lowe T-shirt - XL Phantom Grey",
    "Mystic Rider T-Shirt - XL Seasalt Green",
    "Mystic The Zone S/s T-Shirt - XL Cypress Green",
    "Slingshot Hover Glide FSUP V3",
    "Custom Decor Large Flags",
    "Flying Pig Box  Kite",
    "2021 Mystic Stone Impact Vest - XS Blue/Yellow",
    "Ion Thermo Womens Top - 36/S",
    "Ion Thermo Womens Top - 38/M",
    "Mystic Voltage Sweat 4mm - XL Black",
    "Mystic Voltage Sweat 4mm - XL Night Blue",
    "2021 Crazyfly Hexa II Bindings - Standard",
    "Epic Gear 8-Piece SUP Traction Pad Set - Black",
    "2021 Liquid Force Reign - 53''",
    "Peter Grimm Selene Hat",
    "Peter Grimm SYF Lifeguard Hat",
    "ION Ballistic Shoes 2.5 Round Toe - 5",
    "19 in. WhirliGig Spinner - Red Dragon",
    "20\" Turtle Bike Spinner",
    "2020 Duotone Kite Vest Waist",
    "2022 F One Swing Wing V2 - 5.0 Flame/Abyss CC2",
    "Shore Boards 39\" Pintail-Premium Explorer Dark - Red Wheels",
    "Transparent Tubes w/Handles 38\"",
    "Shore Boards 39\" Pintail Premium North Dark - Blue",
    "Shore Boards 39\" Pintail Premium North Dark - Green Wheels",
    "Winged Ripper Freestyle Complete - 7.0''",
    "23\" Brown Pelican Large Whirligig",
    "Costa Adjustable C-Line Retainer",
    "Cabrinha DA Fusion Hydrofoil - DA850 Demo",
    "2022 Liquid Force Trip - 139",
    "2022 Liquid Force Trip - 135",
    "2022 Liquid Force Board Sleeve - 5'2",
    "2022 Liquid Force Board Sleeve - 6'0",
    "Liquid Force Flare Black T-Shirt - S",
    "Liquid Force Flare Black T-Shirt - M",
    "Liquid Force Flare Black T-Shirt - L",
    "Liquid Force Flare Black T-Shirt - XXL",
    "Liquid Force Graffiti White T-Shirt - L",
    "Liquid Force Graffiti White T-Shirt - S",
    "Liquid Force Illusion Black T-Shirt - L",
    "Liquid Force Illusion Black T-Shirt - M",
    "Liquid Force Illusion Black T-Shirt - S",
    "Liquid Force Illusion Black T-Shirt - XL Black",
    "Liquid Force Illusion Zip Hoodie - S",
    "Liquid Force Illusion Zip Hoodie - M",
    "Liquid Force Illusion Zip Hoodie - XL",
    "Liquid Force Melted L/S White T-Shirt - M",
    "Liquid Force Radiant Grey T-Shirt - S",
    "Liquid Force Radiant Grey T-Shirt - XXL",
    "Liquid Force Radiant Grey T-Shirt - M",
    "Liquid Force Womens Illusion Tank Lilac - S",
    "Phase Five Beach Towel - Blue",
    "Cobian Draino 2 - 10 Charcoal",
    "Cobian Draino 2 - 9 Charcoal",
    "Dakine Peak to Peak T-Shirt - M Teel",
    "Maui Sunset T-Shirt - XL Lead",
    "Cabrinha Fusion H Series Carbon Mast (Build Your Foil) - 70",
    "Flying Pig - 23''",
    "Liquid Force Horizon Foil Set",
    "Zap Skimboards Boardsock - M Striped white",
    "2022 Liquid Force Flash Helmet - M Punk Olive",
    "Zap Beach Towels - Purple/Green Circle Towel",
    "Zap Lazer Skim Traction Tailpad - Black",
    "Zap Lazer Skim Traction Tailpad - White",
    "Zap Mens Charged T-Shirt - L Black",
    "Zap Mens Charged T-Shirt - M Black",
    "Zap Mens Charged T-Shirt - Long Sleeve Large Grey",
    "Zap Mens Charged T-Shirt - Long Sleeve Medium Grey",
    "Zap Skimboards Boardsock - S Green/Black",
    "Zap Skimboards Boardsock - M Green/Black",
    "Zap Waves T-Shirt - Large",
    "Day of the dead - Men",
    "2022 Mystic Stealth Waist Harness - XL Black",
    "2022 Slingshot Hover Glide Carbon Rear Wing Stabilizer 48cm - 48cm",
    "Majestic L/S Rashvest Loosefit - M Black",
    "Sola Wood Skimboards - 35\"",
    "FCS Shaper Series Ci Thruster Reactor - L",
    "Dakine Global Waves Tank - XL Black",
    "Dakine Global Waves Tank - S Black",
    "Dakine Mens Loose Fit S/S Rashguard Crew - XXL",
    "Dakine Mens Loose Fit S/S Rashguard Crew - M",
    "Dakine Mens Loose Fit S/S Rashguard Crew - XL",
    "Dakine Mens Loose Fit S/S Rashguard Crew - S",
    "2021 Mystic Compression Kite Bag",
    "FCS II MB Shaper Series Matt Biolos Thruster Reactor Family - M Blue(Tri-Quad)",
    "Arbor Dropcruiser Photo Longboard",
    "2022 Slingshot SlingWing V3 - 5.5m Orange",
    "2022 Crazyfly Raptor LTD Twintip",
    "Coconut Palm Tree - Small",
    "Starfish Metal Art",
    "OneWheel Pint X",
    "2022 Liquid Force Primo - 4'5",
    "24\" Whirligig Cactus Spinner",
    "Rainbow 301ATLS Mens Sandals - L Black",
    "Rainbow 301ATLS Mens Sandals - S Sierra Brown",
    "Rainbow 301ATLS Mens Sandals - L Sierra Brown",
    "Rainbow 301ATLS Mens Sandals - XXL Sierra Brown",
    "Rainbow 301ATLS Mens Sandals - M Dark Brown",
    "Colorful Parrot Wall Decor - Rainbow",
    "Colorful Pink Cockatoo Wall Decor - Pink",
    "Multi White Stingray Wall Decor - Multi White",
    "Torn Metal Crab Wall Decor - Rustic White",
    "Torn Metal Fish Wall Decor - Rustic White",
    "2021 Phase Five Standard Board Bag - 59\" Medium Sliver",
    "2022 F One Bandit XV - 7m C Abyss/Glacier",
    "2022 Duotone Soleil SLS Twintip",
    "2021 Cabrinha Code Wing Foiling Board",
    "12\"x18\" Conch Republic - Banner",
    "12\"x18\" Happy Hour flag",
    "Seahorse 24\" Spinner",
    "2022 Liquid Force Pod Foilboard 4'4 - 4'4",
    "2022 Cabrinha FX2 - 13m Color 03",
    "2022 Cabrinha Mantis Wing With Windows - 2.5m Color 03",
    "2022 Cabrinha Mantis Wing With Windows - 4.5m Color 01",
    "5 O'Clock Somewhere Beach Garden Linen Flag",
    "Dolphin Wall Art Set of 3",
    "UF Gators Garden Flag",
    "Regal Metal Wall Decor - ALL TYPES - Busy Bee Octagon  Box Metal Art",
    "Regal Metal Wall Decor - ALL TYPES - Call Me Queen Octagon Box Metal Art",
    "Wall Metal Art - All Varieties - Brilliant Dragonfly 3D Legs",
    "Wall Metal Art - All Varieties - Butterflyfish Blue",
    "Wall Metal Art - All Varieties - Damselfish",
    "Wall Metal Art - All Varieties - SM Island Bus",
    "Wall Metal Art - All Varieties - Angel Fish Blue/tur",
    "Wall Metal Art - All Varieties - 48\" Sailfish",
    "Wall Metal Art - All Varieties - 24\" Sailfish",
    "Wall Metal Art - All Varieties - Leaf w/Gecko 26\"",
    "Wall Metal Art - All Varieties - Lg R/B Parrot Pair 30\"",
    "Wall Metal Art - All Varieties - Lg Pair of Parrots",
    "Wall Metal Art - All Varieties - Md 13\" Sunglasses",
    "2022 Liquid Force Index Wakeboard Bindings - 12-15",
    "Ambush Full Deckpad - Merlot",
    "Fish - Strawberry Grouper",
    "Regal Sea Glass - ALL FISH - Butterfly Fish",
    "Regal Sea Glass - ALL FISH - Tuna",
    "Regal Sea Glass - ALL FISH - Sea Bass",
    "Regal Sea Glass - ALL FISH - Yellowtail",
    "2022 Slice Bamboo Series - 5'1",
    "2022 Slice Bamboo Series - 5'3",
    "Cobian Braided Pacifica - 7 Charcoal",
    "Cobian Braided Pacifica - 8 Charcoal",
    "Cobian Floater 2",
    "14 in. Dynamo - Patriotic",
    "Stars & Stripes Windsock - 60 In.",
    "Windsock - Paisley Hummingbird",
    "75\"H Wind Spinner",
    "Manera Seat Cover",
    "Costa C-MONO Retainer",
    "Zap Prowler - 51'",
    "Large Easy Flyer (All) - Woodland fairy",
    "Large Easy Flyer (All) - robot",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil L Series Back Wings - Kai",
    "2022 GoFoil FT-L (Fixed Tail Long) Tail Foil - 17\"",
    "2022 GoFoil FT-L (Fixed Tail Long) Tail Foil - 17\"",
    "2022 GoFoil FT-L (Fixed Tail Long) Tail Foil - 20\"",
    "Single Layer Brown Rubber Top 1\" Mens Sandals - XXL Brown",
    "Single Layer Brown Rubber Top 1\" Mens Sandals - L Brown",
    "Single Layer Brown Rubber Top 1\" Mens Sandals - M Brown",
    "Premier Leather Double Layer Mens Sandals - XL Sierra Brown",
    "Premier Leather Double Layer Mens Sandals - L Sierra Brown",
    "Premier Leather Single Layer Mens Sandals - M eXpresso",
    "Premier Leather Single Layer Mens Sandals - L eXpresso",
    "Premier Leather Single Layer Mens Sandals - XL Sierra Brown",
    "Premier Leather Single Layer Mens Sandals - L Sierra Brown",
    "Premier Leather Single Layer Mens Sandals - M Sierra Brown",
    "Premier Leather Single Layer Mens Sandals - S Sierra Brown",
    "Premier Leather Single Layer Mens Sandals - XXL Sierra Brown",
    "Premier Leather Single Layer Mens Sandals - XXXL Sierra Brown",
    "Premier Leather Single Layer Mens Sandals - XXL Dark Brown",
    "Premier Leather Single Layer Mens Sandals - XL Dark Brown",
    "2023 Cabrinha Drifter - 8m - C2",
    "2023 Cabrinha Drifter - 12m - C1",
    "2023 Cabrinha Nitro Apex - 12m - C5",
    "2023 Cabrinha Ace Hybrid Twintip board - 141 x 43cm",
    "2023 Cabrinha Ace Wood - 145 x 44.5cm",
    "2023 Cabrinha C.O.S. Overdrive Trimlite Control Bar - M/L - 47cm-55cm",
    "2023 Cabrinha Flare Surfboard - 5'4",
    "Cabrinha MKII Foil Kit Wing Pack - H850 Kit",
    "Cabrinha Fusion MKII Alloy Mast (Build Your Foil) - 75cm",
    "Ride Engine Day Strike Foil Bag V3 - 6'0",
    "Airush Session - 10m Slate",
    "2023 Cabrinha Drifter - 10m - B11",
    "2021 Duotone Team Series Hadlow SLS - 139",
    "2022 Fanatic Sky Wing - 4'6",
    "Lift Hydrofoil Mast / Strut (Build Your Foil) - 24",
    "Fix My Kite ER Repair Kit",
    "Lift Surf Series V2 Front Wing - 250",
    "Lift Surf Series V2 Front Wing - 150",
    "Charming Shark Jewelry - Ank/Brac",
    "Charming Shark Jewelry - Ank/Brac Card",
    "2020 GoFoil GL Series Front Wings - 120",
    "2020 GoFoil GL Series Front Wings - 80",
    "2021 Gofoil Flip Tip Tail Wing - 12.5''",
    "2021 Gofoil Flip Tip Tail Wing - 12.5''",
    "GoFoil RS Series Front Wings - 1075",
    "2022 F One Swing Wing V2 - 5.0m Abyss/Flame",
    "2022 F One Swing Wing V2 - 5.0m Abyss/Flame",
    "2022 Liquid Force Trip - 139",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil L Series Back Wings - Kai",
    "2021 GoFoil L Series Back Wings - Kai",
    "Cabrinha Fusion X Series Hydrofoil Base Kit (Build Your Foil) - Carbon 70",
    "Cabrinha 0.2mm Neo Mesh Top - M",
    "Cabrinha 0.2mm Neo Mesh Top - L",
    "Cabrinha 0.2mm Neo Mesh Top - XL",
    "Paddle Surf Hawaii - 10'6 Blue",
    "Cobian Draino 2 - 9 Midnight",
    "Stake Line Winder - 300 ft.  90 lb",
    "2018 Mystic Star Long Sleeve Quickdry - XXL Blue",
    "2018 Mystic Star Long Sleeve Quickdry - S White",
    "2018 Mystic Star Long Sleeve Quickdry - M White",
    "GoFoil RS Series Front Wings - 1000",
    "GoFoil RS Series Front Wings - 1075",
    "GoFoil RS Series Front Wings - 1075",
    "GoFoil RS Series Front Wings - 1075",
    "2023 Cabrinha Spectrum - 152x44",
    "Adult Snorkel Set - Black - PVC",
    "Adult Snorkel Set - Blue - PVC",
    "2022 GoFoil FT-L (Fixed Tail Long) Tail Foil - 10.5\"",
    "2022 GoFoil FT-L (Fixed Tail Long) Tail Foil - 14.5\"",
    "2022 GoFoil FT-L (Fixed Tail Long) Tail Foil - 14.5\"",
    "2022 GoFoil FT-L (Fixed Tail Long) Tail Foil - 17\"",
    "2022 GoFoil FT-L (Fixed Tail Long) Tail Foil - 17\"",
    "2022 GoFoil FT-L (Fixed Tail Long) Tail Foil - 17\"",
    "2022 GoFoil FT-L (Fixed Tail Long) Tail Foil - 17\"",
    "2021 GoFoil FT-S (Fixed Tail Short) Tail Foil - 12.5",
    "2021 GoFoil FT-S (Fixed Tail Short) Tail Foil - 14.5",
    "2021 Mystic Majestic Impact Vest Szip",
    "Jumbo Easy Flyer - Rainbow Orbit",
    "Large Easy Flyer (All) - Unicorn Flowers",
    "Large Easy Flyer (All) - When Pigs Fly",
    "Large Easy Flyer (All) - Orange Dragon",
    "Large Easy Flyer (All) - Tie Dye Butterfly",
    "Large Easy Flyer (All) - Sapphire Dragon",
    "Large Easy Flyer (All) - Passion Dart Frog",
    "Large Easy Flyer (All) - Panda",
    "Oceanus EEL Retractable Reel Board Leash",
    "Charming Shark Jewelry - Anklet / Bracelet",
    "Charming Shark Jewelry - Ankl/Brac",
    "Liquid Force Hinge - XXL Black/Green",
    "Liquid Force Hinge - XXXL Black/Red",
    "JUP Large Sticker",
    "Mystic Multi Spreader Clickbar 4.0 - L/XL",
    "Mystic Multi Spreader Clickbar 4.0 - S/M",
    "Flip-flops metal art",
    "Ride Engine Day Strike Foil Bag V3 - 5'6\"",
    "Ride Engine Day Strike Foil Bag V3 - 7'6\"",
    "Large Easy Flyer (All) - Serena Mermaid",
    "Large Easy Flyer (All) - Mermaid",
    "2022 Phase Five Chip Foil Board - 50''",
    "Airtime Long Life PU Strut Bladder - 90\"",
    "Product's Name",
    "Pro-Tec Ace Water Helmet - XS Red",
    "Dakine Heavy Duty L/S - XXL White",
    "Dakine Storm Neo-Insulator S/S - XL Black",
    "Dakine Watermans L/S",
    "Dakine Offshore S/S",
    "Kitty Kitty Windsock",
    "12\" x 18\" Pirate Flags - Prepare Boarded",
    "12\" x 18\" Pirate Flags - No Guts",
    "12\" x 18\" Pirate Flags - Blackbeard Lives",
    "3' x 5' Pirate Flags - Surrender The Booty",
    "3' x 5' Pirate Flags - Prepare Boarded",
    "NP Edge Wind Top 0.3mm - XS",
    "NP Spice Neo Top 2/1 - 36 Purple/Grey",
    "NP Spice Neo Top 2/1 - 36 Navy/Red",
    "Sea Shell Flag Door Hanger Holder",
    "Liquid Force Divison Boardshorts - 32\"",
    "Dakine Womens Flow Snug Fit Rash Guard - L Black",
    "Dakine Womens Flow Snug Fit Rash Guard - S Kassia",
    "Fall Leaf Spinner",
    "Mermaid House Flag 28 x 40",
    "To Have and To Hold",
    "Sun with Face metal art - XL",
    "Dakine Flow Loose Fit LSL - M Waikiki Snug Fit LS",
    "Mailbox Covers - Sleigh Ride",
    "Mailbox Covers - Makeover-Flag",
    "Mailbox Covers - Flamingo",
    "Mailbox Covers - Octopus",
    "Mailbox Covers - Corgi",
    "Dakine Inlet Loose Fit L/S - M",
    "Dakine Classic Brush T-Shirt - S Charcoal Heather",
    "Local KISS Tank - M",
    "Local KISS Tank - L",
    "Glass Wind Chimes - Sunset Dolphin",
    "Glass Wind Chimes - Endless Summer",
    "Rainbow Open Garden Spinner",
    "Costa Beachside Shirt - Dark Heather",
    "Costa Del Mar - XX Large",
    "Regal Chimes - Turtle",
    "Regal Chimes - Majestic Double Wind 42\"",
    "Regal Chimes - Healing Stone Chime 30 - Amethyst",
    "Costa Del Mar Techsail Rashguard - X Large",
    "Costa Del Mar Techsail Rashguard - XX Large",
    "Llama spinner 24\"",
    "12\"x18\" Nylon Flags - hawaii",
    "12\"x18\" Nylon Flags - ireland",
    "12\"x18\" Nylon Flags - beer",
    "12\"x18\" Nylon Flags - dom rep",
    "Brazil Flag 12x18",
    "Leprechaun Whirligig",
    "Dakine Phillip Morgan Shaka T-Shirt - XL White",
    "Dakine Pineapple III T-Shirt - XL Lead",
    "North Compass Tee - L Black",
    "Shadow Lantern LG - spiral",
    "Rainbow Trout Fish Windsock",
    "2022 Mystic Star L/S Quickdry - L - White",
    "2022 Mystic Star L/S Quickdry - XL - White",
    "2022 Mystic Star L/S Quickdry - M - White",
    "2022 Mystic Star L/S Quickdry - S - White"
];

//Placing columns names in first row
	$delim =  ',' ;
	$csv_output .= 'Product\'s Name' .$delim;
	$csv_output .= 'Model' .$delim;
    $csv_output .= 'Quantity' .$delim;
    $csv_output .= 'Invoice Price' .$delim;
    $csv_output .= 'Receipt Date' .$delim;
    $csv_output .= 'MSRP' .$delim;
    $csv_output .= 'Current Price' .$delim;
    $csv_output .= '% Margin' .$delim;
	$csv_output .= "\n";
//End Placing columns in first row

//start array

//$products_array = array();

// GET ALL PRODUCTS
$get_all_products_query = tep_db_query("SELECT p.*, pd.products_name FROM products p JOIN products_description pd ON p.products_id = pd.products_id JOIN products_to_categories pc on p.products_id = pc.products_id where products_quantity > 0 AND pc.categories_id  <> 884  ORDER BY pd.products_name ASC");
    while($get_all_products = tep_db_fetch_array($get_all_products_query)){
        $products_name = $get_all_products['products_name'];
        $model = $get_all_products['products_model'];
        $qty = (int)$get_all_products['products_quantity'];
        $invoicePrice = (float)$get_all_products['invoice_price'];
        $createdAt = date("d-m-Y", strtotime($get_all_products['products_date_added']));
        $msrp = (float)$get_all_products['products_msrp'];
        $productPrice = (float)$get_all_products['products_price'];
        $margin = (($productPrice - $invoicePrice) / $productPrice) * 100;
        
        // GET ALL PRODUCTS WITH ATTRIBUTES //
        $products_attributes_query = tep_db_query("select * from products_attributes pa JOIN products_to_categories pc on pa.products_id = pc.products_id JOIN products_options_values po ON pa.options_values_id = po.products_options_values_id where pa.options_quantity > 0 AND pc.categories_id  <> 884 AND pa.products_id='" . $get_all_products['products_id'] . "'");
        $check_attribute = tep_db_fetch_array($products_attributes_query);
        if(!empty($check_attribute)){
            $products_attributes_query = tep_db_query("select * from products_attributes pa JOIN products_to_categories pc on pa.products_id = pc.products_id JOIN products_options_values po ON pa.options_values_id = po.products_options_values_id where pa.options_quantity > 0 AND pc.categories_id  <> 884 AND pa.products_id='" . $get_all_products['products_id'] . "'");
            while($products_attributes = tep_db_fetch_array($products_attributes_query)){
                if($products_attributes['products_options_values_name']){
                    $products_name = $get_all_products['products_name'] .' - '. $products_attributes['products_options_values_name'];
                }
                if((float)$products_attributes['options_values_msrp'] > 0){
                    $msrp =  (float)$products_attributes['options_values_msrp'];
                }
                if((float)$products_attributes['options_values_price'] > 0){
                    $productPrice =  (float)$products_attributes['options_values_price'];
                }
                if((float)$products_attributes['options_invoice_price'] > 0){
                    $invoicePrice =  (float)$products_attributes['options_invoice_price'];
                }
                $qty =  $products_attributes['options_quantity'] ?? "";
                if($products_attributes['created_at'] && $products_attributes['created_at'] != '2023-01-16 15:56:31'){
                    $createdAt =  date("d-m-Y", strtotime($products_attributes['created_at']));
                }
                if (
                    strpos($products_name, 'Lessons') == false && 
                    strpos($products_name, 'payout') == false &&
                    strpos($products_name, 'instructor') == false &&
                    strpos($products_name, 'Rental') == false &&
                    strpos($products_name, 'Shipping') == false &&
                    strpos($products_name, 'Warranty ') == false &&
                    strpos($products_name, 'Ebay') == false &&
                    strpos($products_name, 'Labor') == false &&
                    strpos($products_name, 'Gift') == false
                    ) {
                    if (!in_array($products_name, $list)) {
                        $margin = (($productPrice - $invoicePrice) / $productPrice) * 100;
                        $csv_output .= $products_name .$delim;
                        $csv_output .= $model .$delim;
                        $csv_output .= $qty .$delim;
                        $csv_output .= round($invoicePrice,2) .$delim;
                        $csv_output .= date_format(date_create($createdAt),"Y/m/d") .$delim;
                        $csv_output .= round($msrp,2) .$delim;
                        $csv_output .= round($productPrice,2) .$delim;
                        $csv_output .= round($margin,2).'%'.$delim;
                        $csv_output .= "\n";
                    }
                }            
            }
        }else{
            if (
                strpos($products_name, 'Lessons') == false && 
                strpos($products_name, 'payout') == false &&
                strpos($products_name, 'instructor') == false &&
                strpos($products_name, 'Rental') == false &&
                strpos($products_name, 'Shipping') == false &&
                strpos($products_name, 'Warranty ') == false &&
                strpos($products_name, 'Ebay') == false &&
                strpos($products_name, 'Labor') == false &&
                strpos($products_name, 'Gift') == false
                ) {
                    if (!in_array($products_name, $list)) {
                        $csv_output .= $products_name .$delim;
                        $csv_output .= $model .$delim;
                        $csv_output .= $qty .$delim;
                        $csv_output .= round($invoicePrice,2) .$delim;
                        $csv_output .= date_format(date_create($createdAt),"Y/m/d") .$delim;
                        $csv_output .= round($msrp,2) .$delim;
                        $csv_output .= round($productPrice,2) .$delim;
                        $csv_output .= round($margin,2).'%'.$delim;
                        $csv_output .= "\n";
                    }
            }
        }
    }
?>



<?php /*
$delimiter = ','; //parameter for fputcsv
$enclosure = '"'; //parameter for fputcsv
//convert array to csv
$file = fopen('file.csv', 'w+');
foreach ($products_array as $data_line) {
    fputcsv($file, $data_line, $delimiter, $enclosure);
}

$data_read="";
rewind($file);
//read CSV
while (!feof($file)) {
    $data_read .= fread($file, 8192); // will return a string of all data separeted by commas.
}
fclose($file);
echo $data_read;
*/

/*
$delimiter = ','; //parameter for fputcsv
$enclosure = '"'; //parameter for fputcsv
//convert array to csv
$file = fopen('file.csv', 'w+');
foreach ($data as $data_line) {
    fputcsv($file, $data_line, $delimiter, $enclosure);
}

$data_read="";
rewind($file);
//read CSV
while (!feof($file)) {
    $data_read .= fread($file, 8192); // will return a string of all data separeted by commas.
}
fclose($file);
echo $data_read; */

//print
header("Content-Type: application/force-download\n");
header("Cache-Control: cache, must-revalidate");
header("Pragma: public");
header("Content-Disposition: attachment; filename=inventory_price_margin" . date("Ymd") . ".csv");
 print $csv_output;
  exit;

?>
